import { Raleway } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/layouts";

// Import Raleway instead of Geist
const raleway = Raleway({ subsets: ["latin"], preload: false });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.className} antialiased`}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
